### ISSUE TITLE
Need to get the moving block puzzles to work.

### ISSUE THREAD

**Issue by zliebowitz** [stephenwhoskins/Chronos#2]
Have the blocks reset whenever you leave the room.
Only one block should move at a time.

**Comment by zliebowitz** [comment]
@stephenwhoskins  blocks only reset if the puzzle isn't solved?

**Comment by stephenwhoskins** [comment]
Ya, I agree with that.  There's more than one way to "solve" a puzzle, but it's still easy to determine if a puzzle is solved.  For the first puzzle in the game right now stairs will be revealed if you move the blocks correctly.  So for that example if the stairs are not covered with a block, then there is no need to reset the blocks.

**Comment by stephenwhoskins** [comment]
The moving block puzzles work now, but I don't like that you can push two blocks on that same.
