### ISSUE TITLE
Add Missing SFX

### ISSUE THREAD

**Issue by zliebowitz** [stephenwhoskins/Chronos#5]
- [x] sultan walking
- [x] spikes
- [x] arrow traps
- [x] enemy getting hit

**Comment by stephenwhoskins** [comment]
Just pushed a change that adds SFX for the sultan walking.

**Comment by stephenwhoskins** [comment]
Just pushed changes that add SFX for spikes and arrow traps.

Not so sure about the sound for enemies getting hit.

**Comment by stephenwhoskins** [comment]
All the SFX were added, except when enemies get hit.  We agreed it wasn't necessary.
