### ISSUE TITLE
Need a Chronos Battle

### ISSUE THREAD

**Issue by zliebowitz** [stephenwhoskins/Chronos#8]
- [x] Chronos snide remarks: "Time to destroy you. Wait, what, you just finished a fight and this is unfair? Fine, fine, I'll fix you up and then destroy you."

**Comment by stephenwhoskins** [comment]
Why does Chronos want to just keep you inside a castle forever anyway?  Could it be like a Greco-Roman mythology dealy where one of the gods doesn't want harm to come to The Sultan so Chronos's workaround is to confine The Sultan to his labyrinth of sorts?  But once he finds that he has underestimated The Sultan he attempts to end him once and for all?
