### ISSUE TITLE
Add additional weapon

### ISSUE THREAD

**Issue by zliebowitz** [stephenwhoskins/Chronos#9]
maybe a bow/arrow

**Comment by stephenwhoskins** [comment]
Bombs?  We can allow the player to shift between multiple options for their "Z" button ultimately.  But bombs will provide a way to do more puzzles...  Although A Link to the Past effectively pulled off puzzles with the bow and arrow as well.

**Comment by stephenwhoskins** [comment]
This is being handled in new Issues.
